# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsonfriends', '0002_auto_20160919_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_friend', to='friendsonfriends.User'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_friend', to='friendsonfriends.User'),
        ),
    ]
