# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_taker',
        ),
    ]
