# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20160919_1247'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_taker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loginreg.User'),
            preserve_default=False,
        ),
    ]
